---
- name: Verify
  hosts: all
  tasks:
    - name: "Create fake log file"
      file:
        path: "{{ fluentbit_file_input.path }}"
        mode: 0644
        state: touch
    - name: "Generate some fake log"
      lineinfile:
        path: "{{ fluentbit_file_input.path }}"
        line: "This is a test message."
    - name: "Check if fluentbit is installed"
      package:
        name: "{{ fluentbit_pkg_name }}"
        state: present
      register: pkg_install
      check_mode: yes
      failed_when: pkg_install is changed or pkg_install is failed
    - name: "Check if fluentbit service is running"
      service:
        name: "{{ fluentbit_svc_name }}"
        state: started
        enabled: yes
      register: svc_conf
      check_mode: yes
      failed_when: svc_conf is changed or svc_conf is failed
    - name: "Get log file content"
      slurp:
        src: "{{ fluentbit_file_output.path }}/{{ fluentbit_file_output.file }}"
      register: logfile
    - name: "Check that the log file contains the expected strings"
      assert:
        that:
          - "'This is a test message.' in logfile['content'] | b64decode"
          - "'JUST_A_TEST' in logfile['content'] | b64decode"
