---
- name: "123"
  hosts: "proxmox"
  
  pre_tasks:
  - name: Install python3-pip
    ansible.builtin.apt:
      name: python3-pip
  - name: Install multi python packages with version specifiers
    ansible.builtin.pip:
      name:
        - requests
        - proxmoxer

  roles:
    - proxmox
