---
- name: Create new container
  community.general.proxmox:
    vmid: "{{ vmid }}"
    node: "{{ node }}"
    api_user: "{{ api_user }}"
    api_host: "{{ api_host }}"
    api_password: "{{ api_password }}"
    password: "{{ password }}"
    hostname: "{{ hostname }}"
    ostemplate: "{{ ostemplate }}"
    description: "{{ description }}"
    disk: "{{ disk }}"
    cores: "{{ cores }}"
    storage: "{{ storage }}"
    memory: "{{ memory }}"
    netif: "{{ netif }}"
    pubkey: "{{ lookup('file', '~/monitoring_practice_proxmox/keys/rsa4096_key.pub') }}"

- name: Start container
  community.general.proxmox:
    vmid: "{{ vmid }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    state: started

# tasks file for proxmox
